### ISSUE TITLE
rosbot_ekf process crashes on launch

### ISSUE THREAD

**Issue by sjauhri** [husarion/rosbot_ekf#1]
Upon launching with standard mbed_os firmware for the Rosbot2.0 using:
$roslaunch rosbot_ekf all.launch,

the process rosbot_ekf crashes. ROS is running and pose estimation works only with the wheel data and not with the IMU.

Error message:
process[rosbot_ekf-4]: started with pid [1996]
/opt/ros/kinetic/lib/robot_localization/ekf_localization_node: symbol lookup error: /opt/ros/kinetic/lib/libros_filter.so: undefined symbol: _ZlsRSoRKN6XmlRpc11XmlRpcValueE
[rosbot_ekf-4] process has died [pid 1996, exit code 127, cmd /opt/ros/kinetic/lib/robot_localization/ekf_localization_node odometry/filtered:=odom __name:=rosbot_ekf __log:

Could you comment on what the issue could be?

**Comment by lukaszmitka** [comment]
Hello,
Could you make sure that you have installed all required dependencies?
```
sudo apt install ros-kinetic-catkin ros-kinetic-cmake-modules ros-kinetic-diagnostic-msgs ros-kinetic-diagnostic-updater ros-kinetic-eigen-conversions ros-kinetic-geographic-msgs ros-kinetic-geometry-msgs ros-kinetic-message-filters ros-kinetic-message-generation ros-kinetic-message-runtime ros-kinetic-nav-msgs ros-kinetic-nodelet ros-kinetic-roscpp ros-kinetic-roslint ros-kinetic-sensor-msgs ros-kinetic-std-msgs ros-kinetic-std-srvs ros-kinetic-tf2 ros-kinetic-tf2-geometry-msgs ros-kinetic-tf2-ros ros-kinetic-xmlrpcpp
```

Regards,
Łukasz

**Comment by sjauhri** [comment]
Thank you. Update of ros-kinetic solves the issue.
